name: Nx Standard Use Case
on: push
jobs:
  ci:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - run: npm install
      - run: npm nx run-many --target=test --all
      - run: npm nx run-many --target=lint --all
      - run: npm nx run-many --target=build --all --prod