name: Nx Standard Use Case
on: push
defaults:
  run:
    working-directory: ./nx-heroes
jobs:
  ci:
    runs-on: ubuntu-latest
    env:
      NX_BRANCH: $(jq --raw-output .pull_request.number "$GITHUB_EVENT_PATH")
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: '14'
      - run: npm install
      - run: npx nx run-many --target=build --all --prod