name: Nx Standard Use Case
on: push
defaults:
  run:
    working-directory: ./nx-heroes
jobs:
  ci:
    runs-on: ubuntu-latest
    env:
      NX_BRANCH: ${{ github.event.pull_request.number}}
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: '14'
      - run: npm install
      - run: npx nx-cloud start-ci-run
      - run: npx nx run-many --target=build --all --prod
      - run: npx nx-cloud stop-all-agents